### ISSUE TITLE
Add ability to configure running Client on 80/443

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-cli#69]
## Description
As Team Server and Client improvements to make running the client in multi-tenant mode as a service easy, the CLI should be updated to make this work. Changes need to be made to change the port, but also should help configure the user's config.yaml

## Tasks
- [ ] Add command to configure a client to run in multi-tenant mode with flags for http/https support
- [ ] Add ability to read/write the config.yaml file for a client 
- [ ] update start command to read the config.yaml file (if it exists) and modify the port setting.
- [ ] Update docs
